# -*- mode: ruby -*-
# vi: set ft=ruby :

# Add things to playbook.yml
# hosts.ini has to point to the provisioned node
# private_key for the node has to be present as well
# ansible.cfg in ~/home/ansible folder
# cd into  ~/home/ansible folder
# run "ansible-playbook playbook.yml -i hosts.ini" there

Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"
  
    config.vm.define 'ansiblecontrol' do |machine|
      machine.vm.network "private_network", ip: "192.168.33.13"
      machine.vm.hostname = "ansiblecontrol"
      machine.vm.provider "virtualbox" do |v|
        v.name = "ansible_control_vm"
        v.cpus = 1
        v.memory = 2048
      end
      
      machine.vm.synced_folder "./ansible", "/home/vagrant/ansible", create: true,  mount_options: ["dmode=700","fmode=600"]
  
      machine.vm.provision "shell", inline: <<-SHELL
        current="$(ansible --version | grep -oP '(?<=ansible[ ])([0-9]+\.[0-9]+\.[0-9]+)')"
        echo "Current Ansible version:" $current
        
        required="5.9.0"
        echo "Required Ansible version:" $required
        
        if ! [ -x "$(command -v ansible)" ] || [ "$current" = "" ]; then 
            echo "There is no Ansible installed, or it's version is not found."
            echo "Installing Ansible"

            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            sudo python3 -m pip install --upgrade pip
            sudo python3 -m pip install ansible
  
        elif [ "$(printf '%s\n' "$required" "$current" | sort -V | head -n1)" = "$required" ]; then
          echo "Ansible version is ${current} which is same or newer than required ${required}"
        else 
          echo "Used Ansible version is older than the required. Please update it."
        fi

        chmod 0700 ~/.ssh
      SHELL

    end
  end
  